language: rust
rust:
  - stable
script:
  - cargo test --release --features bls381
  - cargo test --release --features bn254
  - cargo test --release --features secp256k1
  - cargo test --release --features ed25519
